FROM ubuntu:20.04

RUN sudo apt-get update -yy && sudo apt-get upgrade -yy
RUN sudo apt-get install clang llvm llvm-dev vim

RUN mkdir /root/workspace
RUN mkdir /root/workspace/src
WORKDIR /root/workspace


